### ISSUE TITLE
TV channels not showing up in sources on Sony KD-49X8000D

### ISSUE THREAD

**Issue by mattclar** [Drafteed/pybravia#9]
Since upgrading to home assistant 2022.9 I can no longer see TV channels listed in the sources of my TV (just inputs and apps) whereas before there was a full  list including tv channels

**Comment by Drafteed** [comment]
Please show debug logs for integration (put there as txt file).

Add this to your **configuration.yaml** file:

```yaml
logger:
  logs:
    homeassistant.components.braviatv: debug
    pybravia: debug
```
Then restart HA and catch logs.
